--your manager is asking all job and their average salary.

select * from EMPLOYEES;

SELECT AVG(SALARY)FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG';

--GET ME AVERAGE SALARY FOR 'AC_ACCOUNT'
SELECT AVG(SALARY) FROM EMPLOYEES
WHERE JOB_ID = 'AC_ACCOUNT';

--GET ME AVERAGE SALARY FOR 'AC_ACCOUNT'
SELECT AVG(SALARY) FROM EMPLOYEES
WHERE JOB_ID = 'AD_ASST';

--
SELECT JOB_ID, AVG(SALARY),COUNT(*), SUM(SALARY), MIN(SALARY), MAX(SALARY)
FROM EMPLOYEES
GROUP BY JOB_ID;




