---- PRACTICE 1 ----


--4. List all the different region_ids in countries table
SELECT DISTINCT FIRST_NAME FROM EMPLOYEES;
SELECT DISTINCT FIRST_NAME, LAST_NAME FROM EMPLOYEES;




--5. Display the salary of the employee Grant Douglas (lastName: Grant, firstName: Douglas)

SELECT SALARY FROM EMPLOYEES
WHERE FIRST_NAME IN='Douglas' AND LAST_NAME = 'Grant';



--6. Display all department information from departments table
-- if the department name values are as below
-- IT , Public Relations , Sales , Executive

SELECT * FROM DEPARTMENTS
WHERE DEPARTMENT_NAME = 'IT' OR DEPARTMENT_NAME = 'Public Relations' OR DEPARTMENT_NAME = 'Sales' OR DEPARTMENT_NAME='Executive';

SELECT * FROM DEPARTMENTS
WHERE DEPARTMENT_NAME IN('IT', 'Public Relations', 'Sales', 'Executive');

SELECT * FROM DEPARTMENTS
WHERE DEPARTMENT_NAME NOT IN ('IT', 'Public Relations', 'Sales', 'Executive');






-- 16 . Display all unique job_id that end with CLERK in employee table

SELECT DISTINCT JOB_ID FROM EMPLOYEES
WHERE JOB_ID LIKE '%CLERK';
/*
 % - MULTIPLE
 _ - SINGLE
 */

SELECT JOB_ID FROM JOBS
WHERE JOB_ID LIKE '%CLERK';



-- 20-4 How many employees are there in each group that have minimum
-- salary of 5000 ?


-- 21. display all job_id and average salary who work as any of these jobs
-- IT_PROG,SA_REP, FI_ACCOUNT, AD_VP
SELECT JOB_ID, AVG (SALARY) FROM EMPLOYEES
WHERE JOB_ID IN('IT_PROG', 'SA_REP', 'FI_ACCOUNT', 'AD_VP')
GROUP BY  JOB_ID;



-- 23. Display total salary for each department except department_id 50, and where

SELECT DEPARTMENT_ID, SUM(SALARY) FROM EMPLOYEES
WHERE DEPARTMENT_ID<>50
GROUP BY DEPARTMENT_ID
HAVING SUM(SALARY)>30000;




---- PRACTICE 2 ----
--8.  Find the 3rd maximum salary from the employees table (do not include duplicates)

--STEP 1 -> FIND ALL SALARY IN DESC ORDERS

SELECT DISTINCT SALARY FROM EMPLOYEES
WHERE ROWNUM<4
ORDER BY SALARY DESC;

--STEP 2 -> FIND ALL 3RD HIGHEST SALARY
SELECT * FROM(SELECT DISTINCT SALARY FROM EMPLOYEES
                                     ORDER BY SALARY DESC)
    WHERE ROWNUM<4;

--STEP 3 -> GET ME ALL EMPLOYEES WHO IS GETTING 3RD MAX SALARY
SELECT * FROM EMPLOYEES
WHERE SALARY=(SELECT MIN(SALARY)FROM (SELECT DISTINCT SALARY FROM EMPLOYEES
                                                             ORDER BY SALARY DESC)WHERE ROWNUM<4);



-- IQ --> GET ME ALL EMPLOYEES WHO IS GETTING 213TH MAX SALARY



--12. Find the 3rd minimum salary from the employees table (do not include duplicates)

--STEPT 1 --> FIND ALL SALARY IN DESC ORDERS
SELECT DISTINCT SALARY FROM EMPLOYEES
ORDER BY SALARY ASC;

--STEPT - 2 --> FIND ALL 3RD HIGHEST SALARY
SELECT MAX(SALARY) FROM (SELECT DISTINCT SALARY FROM EMPLOYEES
                                                ORDER BY SALARY ASC)
WHERE ROWNUM<4;

--STEP - 3 --> GET ME ALL EMPLOYEES WHO IS GETTING 3RD MIN SALARY
SELECT * FROM EMPLOYEES
WHERE SALARY=(SELECT MAX(SALARY) FROM (SELECT DISTINCT SALARY FROM EMPLOYEES
                                                              ORDER BY SALARY ASC)
                                 WHERE ROWNUM<4);


---- PRACTICE 3 ----
SELECT * FROM EMPLOYEES;
--TJ DEPARTMENT --> 50
SELECT * FROM DEPARTMENTS;
-- 50 --> SHIPPING --> 1500
SELECT * FROM LOCATIONS;
--> 1500 --> CALOFORNIA US

-- 1. FIND OUT COUNTRY NAME AND REGION NAME FROM COUNTRIES AND  REGION TABLE

SELECT  REGION_NAME, COUNT(*)
FROM COUNTRIES C INNER JOIN REGIONS R ON C.REGION_ID=R.REGION_ID
GROUP BY REGION_NAME;

--DISPLAY REGIONS WHICH HAS MORE THAN 5 COUNTRY
SELECT  REGION_NAME, COUNT(*)
FROM COUNTRIES C INNER JOIN REGIONS R ON C.REGION_ID=R.REGION_ID
GROUP BY REGION_NAME
HAVING COUNT(*)>5;



-- 3.  FIND OUT DEPARTMENT_NAME AND CITY
SELECT DEPARTMENT_NAME, CITY
FROM DEPARTMENTS D INNER JOIN LOCATIONS L
ON D.LOCATION_ID =  L.LOCATION_ID;



-- 5.  FIND OUT FIRST_NAME, LAST NAME, DEPARTMENT ID , DEPARTMENT NAME FOR DEPARTMENT ID 80 OR 40



-- 7. FIND OUT EMPLOYEES FIRST_NAME , JOB_TITLE , DEPARTMENT_NAME ,  CITY
SELECT FIRST_NAME , JOB_TITLE , DEPARTMENT_NAME ,  CITY
FROM JOBS J
         INNER JOIN EMPLOYEES E ON J.JOB_ID = E.JOB_ID
         INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
         INNER JOIN LOCATIONS L ON D.LOCATION_ID=L.LOCATION_ID;


-- 8. FIND OUT EMPLOYEES FIRST_NAME , JOB_TITLE , DEPARTMENT_NAME ,CITY , COUNTRY_NAME , REGION_NAME

SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,MANAGER_ID FROM EMPLOYEES;

SELECT WORKERS.FIRST_NAME,WORKERS.LAST_NAME,WORKERS.MANAGER_ID,
       MANAGERS.EMPLOYEE_ID,MANAGERS.FIRST_NAME,MANAGERS.LAST_NAME
FROM EMPLOYEES WORKERS  INNER JOIN  EMPLOYEES MANAGERS
                                    ON WORKERS.MANAGER_ID=MANAGERS.EMPLOYEE_ID;


SELECT WORKERS.FIRST_NAME,WORKERS.LAST_NAME,WORKERS.MANAGER_ID,
       MANAGERS.EMPLOYEE_ID,MANAGERS.FIRST_NAME,MANAGERS.LAST_NAME
FROM EMPLOYEES WORKERS  LEFT JOIN  EMPLOYEES MANAGERS
                                   ON WORKERS.MANAGER_ID=MANAGERS.EMPLOYEE_ID;

-- 11 .FIND OUT DEPARTMENT_NAME , LOCATION_ID , AND COUNTRY_NAME INCLUDING THOSE COUNTRIES WITH NO DEPARTMENT

SELECT DEPARTMENT_NAME,L.LOCATION_ID,COUNTRY_NAME from DEPARTMENTS
join LOCATIONS L on DEPARTMENTS.LOCATION_ID = L.LOCATION_ID
RIGHT JOIN COUNTRIES C2 on C2.COUNTRY_ID = L.COUNTRY_ID


----- SELF JOIN ---
-- Display all managers and their managers information
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,MANAGER_ID FROM EMPLOYEES;

SELECT WORKERS.FIRST_NAME,WORKERS.LAST_NAME,WORKERS.MANAGER_ID,
       MANAGERS.EMPLOYEE_ID,MANAGERS.FIRST_NAME,MANAGERS.LAST_NAME
FROM EMPLOYEES WORKERS  INNER JOIN  EMPLOYEES MANAGERS
                                    ON WORKERS.MANAGER_ID=MANAGERS.EMPLOYEE_ID;

-- STEVEN
SELECT WORKERS.FIRST_NAME,WORKERS.LAST_NAME,WORKERS.MANAGER_ID,
       MANAGERS.EMPLOYEE_ID,MANAGERS.FIRST_NAME,MANAGERS.LAST_NAME
FROM EMPLOYEES WORKERS  LEFT JOIN  EMPLOYEES MANAGERS
                                   ON WORKERS.MANAGER_ID=MANAGERS.EMPLOYEE_ID;
