SELECT * FROM EMPLOYEES;
/*
 ORDERBY
 - It allow us to sort data
 */

 SELECT * FROM EMPLOYEES
ORDER BY SALARY;


--SAME QUERY
SELECT

    --DISPALAY ALL THE EMPLOYEES BASED ON THEIR FIRSTNAME DESC
    SELECT * FROM EMPLOYEES
ORDER BY FIRST_NAME DESC ;

-- DISPLAY ALL INFO WHERE AMP ID IS LESS THAN 120 AND ORDER THEM BASED ON SALARY DESC
SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID < 120
ORDER BY SALARY DESC;

--DISPLAY ALL INFORMATION FROM EMPLOYEES AND ORDER THEM BASED ON FIRSTMAME ASC AND LASTNAME
SELECT * FROM EMPLOYEES;
DER BY FIRST_NAME ASC, LAST_NAME DESC;

