SELECT * FROM EMPLOYEES;

--display all information of where first name is david
SELECT * FROM EMPLOYEES
WHERE FRIST_NAME = 'David' AND LAST_NAME = 'Lee';


SELECT FIRST_NAME, LAST_NAME,SALARY
FROM EMPLOYEES
WHERE FIRST_NAME = 'Peter';

SELECT *
FROM EMPLOYEES
WHERE SALARY > 6000;

SELECT EMAIL
FROM EMPLOYEES
WHERE SALARY < 5000;

--display all info from employee who is making more than 7000 and department id is 60

SELECT * FROM EMPLOYEES
WHERE SALARY > 7000 AND DEPARTMENT_ID = 60;

--DISPLAY ALL INFO FROM EMPLOYEEES WHERE SALARY EQUALS OR MORE THAN 3000 AND SALARY EQUALS OR LESS THAN
SELECT * FROM EMPLOYEES
WHERE SALARY >= 3000 AND SALARY <= 7000;

SELECT * FROM EMPLOYEES
WHERE SALARY BETWEEN 3000 AND 7000;

-- DISPLAY ALL INFO FROM EMPLOYEES WHO IS WORKING AS IT_PROG OR MK_MAN
SELECT  * FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG' OR JOB_ID = 'MK_MAN';

--DISPLAY ALL INFO WHERE EMPLOYEE ID 121, 142, 154, 165, 187

SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID = 121 OR EMPLOYEE_ID = 142 OR EMPLOYEE_ID = 154 OR EMPLOYEE_ID = 165 OR EMPLOYEE_ID = 187;

--SOLUTION 2
SELECT * FROM EMPLOYEES
WHERE JOB_ID IN('IT_PROG', 'MK_MAN');

SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID IN(121, 142, 154, 165, 187);

--DISPLAY ALL INFO EXPECT WHERE COUNTRY ID IS US AND IT
SELECT * FROM COUNTRIES
WHERE COUNTRY_ID NOT IN ('US', 'IT');

--IS NULL
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NULL;



