select * from EMPLOYEES;

--Task How many locations we have for each country
SELECT COUNTRY_ID, COUNT(*)
FROM LOCATIONS
GROUP BY COUNTRY_ID;


--TSAK2 DISPLAY ALL EMPLOYEES SALARY IN FOLLOWING FORMAT AS COLUM NAME EMPLOYEES_SALARY
--EX: - sTEVEN MAKES 24000; - NEENA MAKES 17000;

SELECT * FROM EMPLOYEES;

SELECT FIRST_NAME || ' MAKES ' || SALARY as Employees_salary
FROM EMPLOYEES;


