




--display all information from employees who is getting first 5 highest salary
--BAD PRACTICE
--IT IS GETTING DATA BEFORE ORDER THEM BASED ON SALARY

SELECT *
FROM EMPLOYEES
WHERE ROWNUM < 6
ORDER BY SALARY DESC;

--
SELECT * FROM EMPLOYEES ORDER BY SALARY DESC;

SELECT *
FROM(SELECT * FROM EMPLOYEES ORDER BY SALARY DESC)
WHERE ROWNUM < 6;

