select * from EMPLOYEES;

--Display all information who is making max salary
--max salary
SELECT MAX(SALARY) FROM EMPLOYEES; --24000

--IF WE KNOW MAX SALARY CAN WE FIND WHO IS GETTING IT?

SELECT *
FROM EMPLOYEES
WHERE SALARY = 24000;

-- DYNAMIC RESULT?
SELECT *
FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES);

--TASK GIVE ME ALL INFORMATION WHO IS GETTING MIN SALARY
-- MIN SALARY?
SELECT MIN(SALARY)
FROM EMPLOYEES;

-- WHO IS MAKING MIN SALARY?
SELECT * FROM EMPLOYEES
WHERE SALARY = 2100;

-- DYNAMIC QUERY
SELECT *
FROM EMPLOYEES
WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES);

-- DISPALAY ALL INFORMATION WHO IS GETTING SECOND HIGHEST SALARY?
-- FIND MAX SALARY
SELECT MAX(SALARY) FROM EMPLOYEES;

--SECOND MAX SALARY
SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY < 24000;

--WHO IS MAKING 17000;
SELECT *
FROM EMPLOYEES
WHERE SALARY = 17000;




